### ISSUE TITLE
Improve help/documentation and possibly commandline interface

### ISSUE THREAD

**Issue by hannob** [Email-Analysis-Toolkit/fake-mail-server#12]
I find the current usage a bit confusing. When executing the fake-mail-server binary I get a help screen.

The default "running mode" seems to start when running "fake-mail-server setup". However, the help describes that as:
```
  setup      Use this command for initial configuration of an email client
```

The description sounds like this is some dedicated mode for an initial setup.

Furthermore, maybe that should just be the "default mode" (aka that runs when you just run the executable with no parameters)?

**Comment by duesee** [comment]
Yeah. Let's rename `setup` to `run` and say something like `Simulate a benign email server. Useful to setup new clients`.

Let's maybe also merge `test` and `loop-test` adding a `--loop` flag.

I think we can_t/shouldn't have a default subcommand, though. This would exclude the possibility to use positional arguments in other commands.

Specifically, ...

`fake_mail_server test <APPLICATION> <PROTOCOL> <TESTCASES>...`

... would need to be changed to ...

`fake_mail_server test --application <APPLICATION> --protocol <PROTOCOL> --testcases <TESTCASES>...`

... and I don't want to make this change (now).
